name: c0nnect
description: wanna connect?.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


## UI Stuff
  cupertino_icons: ^1.0.0             # IOS Kit
  font_awesome_flutter: ^8.8.1        # Socials
  circular_profile_avatar: ^1.0.6     # Rounded buttons on profile Page
  scroll_snap_list: ^0.6.0            # Sticky emojis
  flutter_tags: "^0.4.9"              # Tags for Addevent
  table_calendar: ^2.3.3              # Calendar Picker
  day_night_time_picker: ^0.3.0+2     # Time Picker
  assorted_layout_widgets: ^3.0.0     # for stacking avatars
  # Animationc
  simple_animations: ^1.3.3
  animate_do: ^1.7.3
  # Navigation
  scrollable_positioned_list: ^0.1.8
  swipedetector: ^1.2.0
  # BAsics
  responsive_container: ^0.0.1
  flutter_svg: ^0.18.0 
  country_picker: ^1.0.4
#  keyboard_visibility: ^0.5.6
  
 
## Backend
  firebase_analytics: ^6.3.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1

  change_app_package_name: ^0.1.2

  get_storage: ^1.4.0
  fluttertoast: ^7.1.8
  dio: ^3.0.10
  image_picker: ^0.6.3+4
  emoji_picker: ^0.1.0
  screenshot: ^0.2.0
  path_provider: ^1.6.18
  get_version: ^0.2.2
  permission_handler: ^5.1.0+2
  contacts_service: ^0.4.6
  url_launcher: ^5.7.10
  firebase_dynamic_links: ^0.6.0+1
  google_maps_flutter: ^1.0.2
  google_map_location_picker: 4.0.0
  camerakit: ^0.0.68
  camera: ^0.5.8+7
  flutter_image_compress: ^0.7.0
  barcode: ^1.17.1
  intl: ^0.16.1
  share: 0.6.5+4
  carousel_slider: ^2.3.1
  location: ^3.0.0
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^4.0.1+1
  cloud_firestore: 0.14.3+1
  video_compress: ^2.1.1
  video_player: ^1.0.1
  video_thumbnail: ^0.2.5+1
  flutter_staggered_grid_view: ^0.3.4
  multi_image_picker: ^4.7.13
  flutter_absolute_path: ^1.0.6
  chewie: 0.12.2
  photo_view: ^0.10.3
  geocoder: ^0.2.1
  flutter_google_places: ^0.2.6
  flutter_countdown_timer: ^3.0.1
  country_codes: ^1.0.3
  timeago: ^2.0.29
  intl_phone_number_input: 0.6.0
  easy_debounce: 1.0.2
  cached_network_image: 2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true